package org.fxapps.kieserverclient.navigation;

public enum Param {

	CONTAINER, REQUEST, RESPONSE, USER, PASSWORD, PROCESS_DEFINITION, TASK_OUT_PARAMS, TASK_IN_PARAMS, USER_TASK_DEFINITION, DETAILS, PROCESS_INSTANCES, PROCESS_INSTANCE, UPDATE_USER_TASKS_ACTION, CALLER_SCREEN;

}
